### ISSUE TITLE
Consider switching to upload jpg rather than png. 

### ISSUE THREAD

**Issue by steveyken** [crossroads/stock.goodcity#1082]
Cloudinary is suggesting we switch from png to jpg to save upload bandwidth. This makes sense.

Consider changing from png to jpg here:

https://github.com/crossroads/stock.goodcity/blob/290d7baad39b3c59ce0d1415a4bcb0a3dfc59a6e/app/components/camera-detect.js#L66-L67

**Comment by steveyken** [comment]
@abulsayyad123 something you might be interested in?

**Comment by abulsayyad123** [comment]
> @abulsayyad123 something you might be interested in?

Sure, @steveyken I can look into this.

**Comment by steveyken** [comment]
Thank you!

**Comment by steveyken** [comment]
Pull request merged. staging app is building so i'll run a test once that's done
